#!/bin/sh -e

# Run this script when initializing Airstack in a new project directory.

# 1. git pull in bootstrap dir to make sure it's using the latest
# 2. Ask for name of project and echo to .airstack/env/AIRSTACK_IMAGE_NAME
#    Default to name of directory.

init() {
  local cwd=$PWD
  local bootstrapdir=~/.airstack/bootstrap/

  echo Make sure Airstack is up-to-date...
  cd $bootstrapdir
  git pull origin master

  cd $cwd

  # TODO: check for each line .gitignore to prevent duplicates; currently not atomic
  echo "Adding to .gitignore\n-----"
  touch .gitignore
  local gitignore=$(cat ${bootstrapdir}templates/gitignore)
  echo "$gitignore\n-----\n"
  echo "$gitignore" >> .gitignore

  if [ ! -f .airstackignore ]; then
    echo "Creating .airstackignore"
    cat ${bootstrapdir}templates/airstackignore > .airstackignore
  fi

  echo Done!
}

init
