#!/bin/sh -e

# TODO: make this interactive rather than automatically installing stuff

${AIRSTACK_HOME:=~/.airstack}

install() {
  local cwd="$PWD"
  mkdir -vp $AIRSTACK_HOME/package/airstack
  cd $AIRSTACK_HOME/package/airstack
  git clone https://github.com/airstack/bootstrap.git
  cd bootstrap
  cd $cwd
  make init
}

install
